name: RevoPurpurUpdater
version: '1.1.2'
main: org.thiagogebrim.revoPurpurUpdater.RevoPurpurUpdater
api-version: '1.21'
load: POSTWORLD
description: Um plugin que atualiza automaticamente o Purpur, ProtocolLib e o LuckPerms
author: thiagogebrim